### ISSUE TITLE
Coq 8.20 support

### ISSUE THREAD

**Issue by palmskog** [rocq-community/fav-ssr#25]
For some reason, Coq 8.20.0 is not supported. Here's the error I got:
```
File "./src/selection.v", line 329, characters 5-53:
Error: The LHS of up_divS
(up_div _.+1 _)
does not match any subterm of the goal
```
If I had to guess, it may be related to how the semantics of SSReflect's `have` changed  - it's now sort-polymorphic and opaque, and one may have to switch to `have @H` instead of `have H` in some places to get desired transparency.

**Comment by ablearthy** [comment]
It happens because [here](https://github.com/coq-community/fav-ssr/blob/4e23c930c8863dc82a786015a68363452ada5b37/src/selection.v#L326) `funelim` unwraps the third case.
In Coq 8.19.0 the goal after `funelim (chop n xs)=>// /H /= {H}IH.` is `size (chop n.+1 (s :: l)) = up_div (size l).+1 n.+1`.
But in 8.20.0 it changes to `(size (chop n.+1 (drop n l))).+1 = up_div (size l).+1 n.+1` (or without simplification to `(size (take n.+1 (s :: l) :: chop n.+1 (drop n.+1 (s :: l)))) = up_div (size l).+1 n.+1`)

It's easy to fix, but I'm looking for a better solution (since I don't know Equations):
```Coq
funelim (chop n xs)=>//.
try rewrite Heqcall. (* Here Heqcall : take n.+1 (s :: l) :: chop n.+1 (drop n.+1 (s :: l)) = chop n.+1 (s :: l) *)
move=> /H /= {H}IH.
```

**Comment by mattam82** [comment]
Sorry, I should have warned more explicitly. Sadly I don't know how to deal with such breaking changes here for an Ltac.
